name: Bit
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  - pip
  # Core
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - requests
  - openpyxl
  - tqdm
  - matplotlib
  - seaborn
  # Tree/Boosting
  - xgboost
  - lightgbm
  # Time-series (ARIMA/VAR)
  - statsmodels
  # GARCH (pip for osx-arm64; conda package not available on this platform)
  # Torch (for LSTM/GRU/CNN/TFT)
  - pytorch
  # Misc runtime helpers
  - numba
  - patsy
  - setuptools
  - wheel
  # Optional: uncomment if you plan to use notebooks
  # - ipykernel
  # - jupyterlab
  # Pip section (kept empty by default)
  - pip:
      # arch is not available on conda for osx-arm64; install via pip
      - arch
      # If PyTorch from conda fails on your platform, you may fallback to pip by uncommenting the next line:
      # - torch
